sudo: required
services:
  - docker

before_install:
  - docker build -t fabiohb/multi-complex-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fabiohb/multi-complex-client npm run test -- --coverage

after_success:
  - docker build -t fabiohb/multi-complex-client ./client
  - docker build -t fabiohb/multi-complex-nginx ./nginx
  - docker build -t fabiohb/multi-complex-server ./server
  - docker build -t fabiohb/multi-complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fabiohb/multi-complex-client
  - docker push fabiohb/multi-complex-nginx
  - docker push fabiohb/multi-complex-server
  - docker push fabiohb/multi-complex-worker

# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react-example"
#   env: "docker-react-example-env"
#   bucket_name: ""
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY